from typing import Any

class CancelledError(Exception): ...

DEBUG: int

class EventLoop:
    def call_at_(self, *args) -> Any: ...
    def call_later(self, *args) -> Any: ...
    def call_later_ms(self, *args) -> Any: ...
    def call_soon(self, *args) -> Any: ...
    def close(self, *args) -> Any: ...
    def create_task(self, *args) -> Any: ...
    def run_forever(self, *args) -> Any: ...
    def run_until_complete(self, *args) -> Any: ...
    def stop(self, *args) -> Any: ...
    def time(self, *args) -> Any: ...
    def wait(self, *args) -> Any: ...

class IORead:
    def handle(self, *args) -> Any: ...

class IOReadDone:
    def handle(self, *args) -> Any: ...

class IOWrite:
    def handle(self, *args) -> Any: ...

class IOWriteDone:
    def handle(self, *args) -> Any: ...

class PollEventLoop: ...
